In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("CKD.csv")

In [3]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [4]:
df.describe()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc
count,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000
mean,51.492308,76.459948,0.899749,0.395990,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597
std,16.995379,13.492053,1.314769,1.041155,74.864224,49.336046,5.623758,9.215829,2.823323,2.715753,8.157274,2526.204544,0.841006
min,2.000000,50.000000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000,9.000000,2200.000000,2.100000
25%,42.000000,70.000000,0.000000,0.000000,101.000000,27.000000,0.900000,135.000000,4.000000,10.850000,34.000000,6950.000000,4.500000
50%,54.000000,76.459948,0.000000,0.000000,127.000000,44.000000,1.400000,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597
75%,64.000000,80.000000,2.000000,0.000000,150.000000,62.500000,3.077356,141.000000,4.800000,14.600000,44.000000,9400.000000,5.100000
max,90.000000,180.000000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000,54.000000,26400.000000,8.000000

In [5]:
df.shape

(399, 25)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             399 non-null    float64
 1   bp              399 non-null    float64
 2   sg              399 non-null    object
 3   al              399 non-null    float64
 4   su              399 non-null    float64
 5   rbc             399 non-null    object
 6   pc              399 non-null    object
 7   pcc             399 non-null    object
 8   ba              399 non-null    object
 9   bgr             399 non-null    float64
 10  bu              399 non-null    float64
 11  sc              399 non-null    float64
 12  sod             399 non-null    float64
 13  pot             399 non-null    float64
 14  hrmo            399 non-null    float64
 15  pcv             399 non-null    float64
 16  wc              399 non-null    float64
 17  rc              399 non-null    float64
 18  htn             399 non-null    object
 19  dm              399 non-null    object
 20  cad             399 non-null    object
 21  appet           399 non-null    object
 22  pe              399 non-null    object
 23  ane             399 non-null    object
 24  classification  399 non-null    object
dtypes: float64(13), object(12)
memory usage: 78.1+ KB

In [7]:
df = pd.get_dummies(df, columns = ["cad","appet","pe","sg","rbc","pc","pcc","ba","htn","dm","ane"], drop_first=True)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
col_features = ["age","bp","al","su","bgr","bu","sc","sod","pot","hrmo","pcv","wc","rc"]

In [11]:
df[col_features] = scaler.fit_transform(df[col_features])

In [12]:
df

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,ane_yes
0,-2.915760e+00,0.000000,1.599435,-0.380815,0.000000,2.884037e-16,7.906578e-17,-3.087882e-15,0.000000,-1.309830e-15,...,True,False,False,True,False,False,False,False,False,False
1,-2.856847e+00,0.000000,0.837890,-0.380815,0.000000,-7.200953e-01,-4.232652e-01,-3.087882e-15,0.000000,-6.703254e-01,...,True,False,False,True,True,False,False,False,False,False
2,-2.797933e+00,0.000000,0.076345,-0.380815,-0.656847,-6.998006e-01,-4.410692e-01,5.119861e-02,-0.080589,-1.910358e-01,...,False,False,False,True,True,False,False,False,False,False
3,-2.739020e+00,0.000000,0.076345,-0.380815,0.000000,-8.418629e-01,-4.232652e-01,5.119861e-02,-0.506154,-1.628904e+00,...,False,True,False,True,True,False,False,False,False,True
4,-2.739020e+00,-1.963613,-0.685199,-0.380815,0.000000,-6.592114e-01,-4.410692e-01,-3.087882e-15,0.000000,-2.647727e-01,...,True,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,-4.186049e-16,-0.479398,-0.685199,-0.380815,0.948067,-4.359708e-01,-3.164410e-01,1.598438e-01,-0.328835,-6.693691e-03,...,False,False,False,True,True,False,False,False,False,False
395,-4.186049e-16,-0.479398,-0.685199,1.542540,0.961442,2.134565e-01,-4.938055e-02,-3.087882e-15,0.000000,-1.407694e+00,...,True,False,False,True,True,False,False,True,True,True
396,-4.186049e-16,-0.479398,1.599435,-0.380815,-0.509730,1.167303e+00,5.203484e-01,-3.833821e-01,-0.683472,-1.260220e+00,...,True,False,False,True,True,False,False,True,True,False
397,-4.186049e-16,1.004817,-0.685199,-0.380815,0.787576,4.569917e-01,6.627806e-01,4.857794e-01,0.309512,-1.481431e+00,...,False,False,False,True,True,False,False,True,True,True
398,-4.186049e-16,0.262710,-0.685199,-0.380815,-0.643473,-1.721410e-01,-3.698531e-01,2.684890e-01,0.132193,1.394307e+00,...,False,False,False,True,True,False,False,False,False,False

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
independant = df.drop("classification", axis = 1)

In [15]:
independant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          399 non-null    float64
 1   bp           399 non-null    float64
 2   al           399 non-null    float64
 3   su           399 non-null    float64
 4   bgr          399 non-null    float64
 5   bu           399 non-null    float64
 6   sc           399 non-null    float64
 7   sod          399 non-null    float64
 8   pot          399 non-null    float64
 9   hrmo         399 non-null    float64
 10  pcv          399 non-null    float64
 11  wc           399 non-null    float64
 12  rc           399 non-null    float64
 13  cad_yes      399 non-null    bool
 14  appet_yes    399 non-null    bool
 15  pe_yes       399 non-null    bool
 16  sg_b         399 non-null    bool
 17  sg_c         399 non-null    bool
 18  sg_d         399 non-null    bool
 19  sg_e         399 non-null    bool
 20  rbc_normal   399 non-null    bool
 21  pc_normal    399 non-null    bool
 22  pcc_present  399 non-null    bool
 23  ba_present   399 non-null    bool
 24  htn_yes      399 non-null    bool
 25  dm_yes       399 non-null    bool
 26  ane_yes      399 non-null    bool
dtypes: bool(14), float64(13)
memory usage: 46.1 KB

In [16]:
dependant = df["classification"]

In [17]:
dependant.value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    independant, dependant, 
    test_size=0.2,      # 20% of data goes to the test set
    random_state=42,    # Ensures you get the same split every time
    stratify=dependant          # Recommended: maintains the same ratio of classes as the original data
)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier

In [20]:
model1 = LogisticRegression()
model2 = GaussianNB()
model3 = DecisionTreeClassifier()
model4 = LinearSVC()
model5 = KNeighborsClassifier()
model1.fit(X_train, y_train)

LogisticRegression()

In [21]:
model2.fit(X_train, y_train)

GaussianNB()

In [22]:
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [23]:
model4.fit(X_train, y_train)

LinearSVC()

In [24]:
model5.fit(X_train, y_train)

KNeighborsClassifier()

In [25]:
y1_pred = model1.predict(X_test)

In [26]:
y2_pred = model2.predict(X_test)

In [27]:
y3_pred = model3.predict(X_test)

In [28]:
y4_pred = model4.predict(X_test)

In [30]:
y5_pred = model5.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix 
cm1 = confusion_matrix(y_test, y1_pred)
print(classification_report(y_test, y1_pred))

              precision    recall  f1-score   support

          no       1.00      1.00      1.00        30
         yes       1.00      1.00      1.00        50

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [33]:
cm2 = confusion_matrix(y_test, y2_pred)
print(classification_report(y_test, y2_pred))

              precision    recall  f1-score   support

          no       0.97      1.00      0.98        30
         yes       1.00      0.98      0.99        50

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [ ]:
cm3 = confusion_matrix(y_test, y3_pred)
print(classification_report(y_test, y3_pred))

              precision    recall  f1-score   support

          no       0.97      1.00      0.98        30
         yes       1.00      0.98      0.99        50

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [34]:
cm4 = confusion_matrix(y_test, y4_pred)
print(classification_report(y_test, y4_pred))

              precision    recall  f1-score   support

          no       0.97      1.00      0.98        30
         yes       1.00      0.98      0.99        50

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [35]:
cm5 = confusion_matrix(y_test, y5_pred)
print(classification_report(y_test, y5_pred))

              precision    recall  f1-score   support

          no       0.88      1.00      0.94        30
         yes       1.00      0.92      0.96        50

    accuracy                           0.95        80
   macro avg       0.94      0.96      0.95        80
weighted avg       0.96      0.95      0.95        80